backend:
  name: git-gateway
  branch: master

site_url: https://new-mlab.netlify.app/

media_folder: src/images
public_folder: src/markdown

collections:
  - name: "news"
    label: "News"
    folder: "src/markdown/news"
    create: true
    path: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "date", format: "MMM D, YY" }
      - { label: "Image", name: "thumb", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Talent", "Startup", "Entrepreneurship"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "theTech"
    label: "Tech"
    folder: "src/markdown/theTech"
    create: true
    fields:
      - { label: "App Name", name: "appName", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "App Icon", name: "icon", widget: "image", choose_url: true }
      - {
          label: "Screenshot",
          name: "screenshot",
          widget: "image",
          allow_multiple: false,
          choose_url: true,
        }
  - name: "locations"
    label: "Locations"
    folder: "src/markdown/locations"
    create: true
    fields:
      - { label: "City", name: "city", widget: "string" }
      - { label: "Image", name: "featureImage", widget: "image" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Programmes", name: "programmes", widget: "list" }
      - { label: "Telephone", name: "tel", widget: "string" }
      - { label: "Physical Address", name: "physicalAddress", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "aboutUs"
    label: "About Us"
    folder: "src/markdown/about-mlab"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "What We Do Sections"
    label: "what-we-do"
    folder: "src/markdown/wwdSections"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wwdSections"
    label: What We Do Sections
    folder: "src/markdown/wwdSections"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumb", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  
