backend:
  name: git-gateway
  branch: master

site_url: https://mobilelab.netlify.app

media_folder: src/images
public_folder: ../../images

collections:
  - name: "news"
    label: "News"
    folder: "src/markdown/news"
    filter: { field: "timeStamp" }
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "timeStamp", widget: "date" }
      - { label: "Image", name: "featureImage", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "Tech Ecosystems",
              "Tech Skills",
              "Tech Start-Ups",
              "Tech Solutions",
            ],
        }
      - { label: "Tag(s)", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "theTech"
    label: "App Projects"
    folder: "src/markdown/theTech"
    create: true
    fields:
      - { label: "App Name", name: "appName", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "App Icon", name: "icon", widget: "image", choose_url: true }
      - {
          label: "Screenshot",
          name: "screenshot",
          widget: "image",
          allow_multiple: false,
          choose_url: true,
        }
  - name: "team"
    label: "mLab Team"
    folder: "src/markdown/team"
    create: true
    fields:
      - { label: "Full Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - {
          label: "Picture",
          name: "profilePicture",
          widget: "image",
          choose_url: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "locations"
    label: "Locations"
    folder: "src/markdown/locations"
    create: true
    fields:
      - { label: "City", name: "city", widget: "string" }
      - { label: "Province", name: "province", widget: "string" }
      - { label: "Image", name: "featureImage", widget: "image" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Programmes", name: "programmes", widget: "list" }
      - { label: "Telephone", name: "tel", widget: "string" }
      - { label: "Physical Address", name: "physicalAddress", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "aboutUs"
    label: "About Us"
    folder: "src/markdown/about-mlab"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wwdSections"
    label: "Pillers"
    folder: "src/markdown/wwdSections"
    create: true
    fields:
      - { label: "Priority", name: "priority", widget: "number" }
      - { label: "Icon", name: "icon", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Contact Emain", name: "email", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Short Text", name: "shortText", widget: "string" }
      - { label: "Video", name: "video", widget: "string", required: false }
      - { label: "Background", name: "featureImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "mcollaboration"
    label: Partners
    folder: "src/markdown/mcollaboration"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "provincialPartners"
    label: "Provincial Partners"
    folder: "src/markdown/provincial-partners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumb", name: "thumb", widget: "image" }
  - name: "foundingPartners"
    label: "Founding Partners"
    folder: "src/markdown/founding-partners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumb", name: "thumb", widget: "image" }
  - name: "partnershipContacts"
    label: "Partnership Contacts"
    folder: "src/markdown/partnershipContacts"
    create: true
    fields:
      - { label: "Enquiry", name: "enquiry", widget: "string" }
      - { label: "Employee Contact", name: "contact", widget: "string" }
  - name: "publications"
    label: "Publications"
    folder: "src/markdown/publications"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "link" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Can embed?",
          name: "embed",
          widget: "boolean",
          default: false,
        }
  - name: "barStats"
    label: "Impact Bar Stats"
    folder: "src/markdown/impactBarStats"
    create: true
    fields:
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Icon", name: "image", widget: "image" }
      - {
          label: "Percentage",
          name: "percentage",
          widget: "number",
          value_type: "int",
          default: 1,
          min: 1,
          max: 100,
          step: 1,
        }
  - name: "banners"
    label: "Banners"
    folder: "src/markdown/banners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Registration", name: "registration", widget: "string" }
      - { label: "Body", name: "body", widget: "string" }
  - name: "whatWeDo"
    label: "WWD Sections(Old)"
    folder: "src/markdown/whatWeDo"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Thumb", name: "featureImage", widget: "image" }
      - { label: "Video Link", name: "video", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "techSolutionsApplication"
    label: "Tech Solutions Applications"
    file: "src/markdown/tech-solutions/tech-solutions.md"
    create: false
    fields:
      - { label: "Open", name: "open", widget: "boolean" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Application Url", name: "link", widget: "string" }
