backend:
  name: git-gateway
  branch: master
# https://mobilelab.netlify.app/
site_url: https://mlab.co.za/

media_folder: src/images
public_folder: ../../images

collections:
  - name: "banners"
    label: "Banners"
    folder: "src/markdown/banners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Registration", name: "registration", widget: "string" }
      - { label: "Body", name: "body", widget: "string" }
  - name: "partners-list"
    label: "Activity Partners"
    folder: "src/markdown/partners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "string" }
  - name: "aboutUs"
    label: "About Us"
    folder: "src/markdown/about-mlab"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "team"
    label: "Team"
    folder: "src/markdown/team"
    create: true
    fields:
      - { label: "Full Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - {
          label: "Picture",
          name: "profilePicture",
          widget: "image",
          choose_url: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "tech-solution"
    label: "Tech Solutions Application"
    folder: "src/markdown/tech-solution"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Open", name: "open", widget: "boolean" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "tech-skills"
    label: "Tech Skills Application"
    folder: "src/markdown/tech-skills"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Open", name: "open", widget: "boolean" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "tech-startups"
    label: "Tech Startups Application"
    folder: "src/markdown/tech-startups"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Open", name: "open", widget: "boolean" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "wwdSections"
    label: What We Do Sections
    folder: "src/markdown/wwdSections"
    create: true
    fields:
      - { label: "Icon", name: "icon", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Contact Emain", name: "email", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Short Text", name: "shortText", widget: "string" }
      - { label: "Background", name: "featureImage", widget: "image" }
      - { label: "Video", name: "video", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "impact"
    label: "Our Impact"
    folder: "src/markdown/impactBarStats"
    create: true
    fields:
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "icon", name: "Icon", widget: "image" }
  - name: "theTech"
    label: "Tech"
    folder: "src/markdown/theTech"
    create: true
    fields:
      - { label: "App Name", name: "appName", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "App Icon", name: "icon", widget: "image", choose_url: true }
      - {
          label: "Screenshot",
          name: "screenshot",
          widget: "image",
          allow_multiple: false,
          choose_url: true,
        }
  - name: "foundingPartners"
    label: "Founding Partners"
    folder: "src/markdown/founding-partners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumb", name: "thumb", widget: "image" }
  - name: "partners"
    label: "Partners Content"
    folder: "src/markdown/mcollaboration"
    create: false
    fields:
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "src/markdown/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "team",
          searchFields: ["name", "name"],
          valueField: "name",
        }
      - { label: "Date", name: "timeStamp", widget: "datetime" }
      - { label: "Image", name: "featureImage", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          searchFields: ["name"],
          valueField: "name",
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "resources"
    label: "Resources"
    folder: "src/markdown/resources"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Drive Preview Link", name: "link", widget: "string" }
      - {
          label: "Document",
          name: "file",
          widget: "file",
          media_folder: "src/assets/resources",
          required: false,
        }
  - name: "projects"
    label: "Projects"
    folder: "src/markdown/projects"
    create: true
    fields:
      - { label: "Thumbnail", name: "image", widget: "image", choose_url: true }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Client & Country of Assignment",
          name: "cca",
          widget: "string",
        }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "From", name: "from", widget: "date" }
      - { label: "To", name: "to", widget: "date" }
      - { label: "Link", name: "link", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "wwdSections",
          searchFields: ["title"],
          valueField: "title",
        }
      - { label: "Android", name: "android", widget: "boolean" }
      - { label: "iOS", name: "ios", widget: "boolean" }
      - { label: "Web", name: "web", widget: "boolean" }
  - name: "aiMashupWebinars"
    label: "AI Mashup Webinars"
    folder: "src/markdown/webinars"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
  - name: "categories"
    label: "Categories"
    folder: "src/markdown/categories"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
  - name: "partnershipContacts"
    label: "Partnership Contacts"
    folder: "src/markdown/partnershipContacts"
    create: true
    fields:
      - { label: "Priority", name: "priprity", widget: "number" }
      - { label: "Enquiry", name: "enquiry", widget: "string" }
      - { label: "Employee Contact", name: "contact", widget: "string" }
  - name: "publications"
    label: "Publications"
    folder: "src/markdown/publications"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "link" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - {
          label: "Can embed?",
          name: "embed",
          widget: "boolean",
          default: false,
        }
  - name: "locations"
    label: "Locations"
    folder: "src/markdown/locations"
    create: true
    fields:
      - { label: "City", name: "city", widget: "string" }
      - { label: "Province", name: "province", widget: "string" }
      - { label: "Image", name: "featureImage", widget: "image" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Programmes", name: "programmes", widget: "list" }
      - { label: "Telephone", name: "tel", widget: "string" }
      - { label: "Physical Address", name: "physicalAddress", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
