backend:
  name: git-gateway
  branch: master

site_url: https://new-mlab.netlify.app/

media_folder: src/images
public_folder: ../../images

collections:
  - name: "news"
    label: "News"
    folder: "src/markdown/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "timeStamp", widget: "date", format: "D MMMM, YY" }
      - { label: "Image", name: "featureImage", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Talent", "Startup", "Entrepreneurship"],
        }
      - { label: "Tag(s)", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "theTech"
    label: "Tech"
    folder: "src/markdown/theTech"
    create: true
    fields:
      - { label: "App Name", name: "appName", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "App Icon", name: "icon", widget: "image", choose_url: true }
      - {
          label: "Screenshot",
          name: "screenshot",
          widget: "image",
          allow_multiple: false,
          choose_url: true,
        }
  - name: "locations"
    label: "Locations"
    folder: "src/markdown/locations"
    create: true
    fields:
      - { label: "City", name: "city", widget: "string" }
      - { label: "Image", name: "featureImage", widget: "image" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Programmes", name: "programmes", widget: "list" }
      - { label: "Telephone", name: "tel", widget: "string" }
      - { label: "Physical Address", name: "physicalAddress", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: "aboutUs"
    label: "About Us"
    folder: "src/markdown/about-mlab"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "wwdSections"
    label: What We Do Sections
    folder: "src/markdown/wwdSections"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumb", name: "thumb", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "barStats"
    label: "Impact Bar Stats"
    folder: "src/markdown/impactBarStats"
    create: true
    fields:
      - { label: "Label", name: "label", widget: "string" }
      - {
          label: "Percentage",
          name: "percentage",
          widget: "number",
          value_type: "int",
          default: 1,
          min: 1,
          max: 100,
          step: 1,
        }
  - name: "banners"
    label: "Banners"
    folder: "src/markdown/banners"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Registration", name: "registration", widget: "string" }
      - { label: "Body", name: "body", widget: "string" }
  - name: "whatWeDo"
    label: "whatWeDo"
    folder: "src/markdown/whatWeDo"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumb", name: "featureImage", widget: "image" }
      - { label: "Video Link", name: "video", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
